name: FastAPI CI

on:
  push:
    branches:
      - main

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    # Run if:
    # 1) Direct push to main
    # 2) PR closed AND merged into main
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest

    steps:

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Trigger Jenkins Build (with crumb)
        run: |
          CRUMB_JSON=$(curl -s \
            -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            -H "Accept: application/json" \
            "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json")

          CRUMB_FIELD=$(echo "$CRUMB_JSON" | jq -r .crumbRequestField)
          CRUMB_VALUE=$(echo "$CRUMB_JSON" | jq -r .crumb)

          curl -X POST \
            -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            -H "$CRUMB_FIELD: $CRUMB_VALUE" \
            "${{ secrets.JENKINS_URL }}/job/FastAPI/build"
