name: FastAPI CI

on:
  push:
    branches:
      - main

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    # Run if:
    # 1) Direct push to main
    # 2) PR closed AND merged into main
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest

    steps:

      - name: Debug Jenkins URL
        run: |
          echo "URL='${{ secrets.JENKINS_URL }}'"
          echo "Length: ${#JENKINS_URL}"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}


      - name: Trigger Jenkins Build
        run: |
          curl --fail --show-error \
            -X POST \
            --data "token=${{ secrets.JENKINS_JOB_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/job/FastAPI/build"
